language: go
go:
  - 1.9.x
  - 1.10.x
  - tip
env:
  - GOMAXPROCS=4 GORACE=halt_on_error=1
install:
  - go get -u github.com/golang/dep/cmd/dep
  - go install github.com/golang/dep/cmd/dep
  - dep ensure
script:
  - go test -race -v ./...
